addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow
  postgresql: "9.3"

language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

env:
  matrix:
  - VERSION="8.0" LINT_CHECK="1"
  - VERSION="8.0" ODOO_REPO="odoo/odoo" LINT_CHECK="0"
  global:
    secure: "HLfds+sQG4JcM52D7b/sTemGvBlVNdfGc4XvJ+py2rx25F4BWojpbOYx44nSiUjBO9U6Eo5kwiK0mWEXoPGg6trQcbiur9kgHrV3+hydlUUKe2/P/mnoP2JAxtu0JBSLxNcG40FdIwEE3Sd0w/ocmxMOp3RmOOVacAY48eWYeh8="


install:
  - git config --global user.email "cgstudiomap@gmail.com"
  - git config --global user.name "cgstudiomap"

  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${HOME}/cgstudiomap/cgstudiomap/main:${HOME}/cgstudiomap/cgstudiomap/main/bin:${PATH}
  - travis_install_nightly
#  geoengine dependencies + our modules.
  - pip install geojson Shapely pygeocoder phonenumbers validate_email pyDNS django zc.buildout
#  - sudo apt-get -q -y install postgis python-geoip

#  Install of GeoIP
  - wget https://github.com/maxmind/geoip-api-c/releases/download/v1.6.2/GeoIP-1.6.2.tar.gz
  - tar xzf GeoIP-1.6.2.tar.gz
  - cd GeoIP-1.6.2
  - ./configure --prefix /opt/geoip-1.6.2
  - make
  - make check
  - sudo make install
  - cd ..

# buildout install
  - cd main
  - ./install.sh
#  - createdb -T openerp_test cgstudiomap_test
  - createdb cgstudiomap_test

before_script:
#  - if [ -n "${ODOO_REPO}" ] ; then wget --no-check-certificate -O ${HOME}/5618.patch http://patch-diff.githubusercontent.com/raw/odoo/odoo/pull/5618.patch ; fi
#  - if [ -n "${ODOO_REPO}" ] ; then IFS="/" read -a REPO <<< "${ODOO_REPO}"; patch -f -d "${HOME}/${REPO[1]}-${VERSION}" -p1 -i ${HOME}/5618.patch ; fi
  - if [ -n "${ODOO_REPO}" ] ; then wget --no-check-certificate -O ${HOME}/5620.patch http://patch-diff.githubusercontent.com/raw/odoo/odoo/pull/5620.patch ; fi
  - if [ -n "${ODOO_REPO}" ] ; then IFS="/" read -a REPO <<< "${ODOO_REPO}"; patch -f -d "${HOME}/${REPO[1]}-${VERSION}" -p1 -i ${HOME}/5620.patch ; fi
  - psql -c "createuser --superuser --createdb --username postgres --no-createrole -w odoo8dev"
  - psql -c "psql -c \"ALTER USER odoo8dev WITH PASSWORD 'odoo'\""
  - psql -U postgres -c "create extension postgis"
script:
#  - travis_run_tests

after_success:
  - coveralls

script:
#  - travis_run_tests
  - ./bin/start_odoo -d cgstudiomap_test --stop-after-init -i all --test-enable --log-level=test

